export type Pessoa = {
  id: string;
  nomeCompleto: string;
  categoria: string;
  regional: string;
};

export const pessoas: Pessoa[] = [
  { id: '1001', nomeCompleto: 'Ana Paula Silva', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1002', nomeCompleto: 'João Pedro Santos', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1003', nomeCompleto: 'Maria Clara Oliveira', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1004', nomeCompleto: 'Carlos Eduardo Souza', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1005', nomeCompleto: 'Fernanda Lima Rodrigues', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1006', nomeCompleto: 'Lucas Gabriel Ferreira', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1007', nomeCompleto: 'Juliana Alves Costa', categoria: 'ADULTO', regional: 'CEARA' },
  { id: '1008', nomeCompleto: 'Marcos Vinicius Pereira', categoria: 'SENIOR', regional: 'RIO GRANDE DO SUL' },
  { id: '1009', nomeCompleto: 'Leticia Martins Gomes', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1010', nomeCompleto: 'Rafael Henrique Ribeiro', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1011', nomeCompleto: 'Amanda Caroline Carvalho', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1012', nomeCompleto: 'Felipe Augusto Almeida', categoria: 'JOVEM', regional: 'DISTRITO FEDERAL' },
  { id: '1013', nomeCompleto: 'Beatriz Soares Silva', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1014', nomeCompleto: 'Thiago Mendes Santos', categoria: 'SENIOR', regional: 'RIO DE JANEIRO' },
  { id: '1015', nomeCompleto: 'Mariana Fernandes Oliveira', categoria: 'JOVEM', regional: 'MINAS GERAIS' },
  { id: '1016', nomeCompleto: 'Diego Barbosa Souza', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1017', nomeCompleto: 'Camila Rocha Rodrigues', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1018', nomeCompleto: 'Rodrigo Castro Ferreira', categoria: 'SENIOR', regional: 'PERNAMBUCO' },
  { id: '1019', nomeCompleto: 'Bruna Nunes Alves', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1020', nomeCompleto: 'Mateus Correia Costa', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1021', nomeCompleto: 'Larissa Vieira Pereira', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1022', nomeCompleto: 'Guilherme Pinto Ribeiro', categoria: 'JOVEM', regional: 'GOIAS' },
  { id: '1023', nomeCompleto: 'Jessica Farias Gomes', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1024', nomeCompleto: 'Leonardo Cavalcante Carvalho', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1025', nomeCompleto: 'Vanessa Monteiro Almeida', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1026', nomeCompleto: 'Marcelo Dias Silva', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1027', nomeCompleto: 'Renata Moura Santos', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1028', nomeCompleto: 'Vitor Mendes Oliveira', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1029', nomeCompleto: 'Patricia Cardoso Souza', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1030', nomeCompleto: 'Eduardo Teixeira Rodrigues', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1031', nomeCompleto: 'Natália Silva Ferreira', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1032', nomeCompleto: 'Bruno Santos Alves', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1033', nomeCompleto: 'Carolina Oliveira Costa', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1034', nomeCompleto: 'Ricardo Souza Pereira', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1035', nomeCompleto: 'Tatiane Rodrigues Ribeiro', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1036', nomeCompleto: 'Gustavo Ferreira Gomes', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1037', nomeCompleto: 'Daniela Alves Carvalho', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1038', nomeCompleto: 'Alexandre Pereira Almeida', categoria: 'SENIOR', regional: 'RIO DE JANEIRO' },
  { id: '1039', nomeCompleto: 'Isabela Costa Silva', categoria: 'JOVEM', regional: 'MINAS GERAIS' },
  { id: '1040', nomeCompleto: 'Fernando Ribeiro Santos', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1041', nomeCompleto: 'Paula Gomes Oliveira', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1042', nomeCompleto: 'Daniel Carvalho Souza', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1043', nomeCompleto: 'Gabriela Almeida Rodrigues', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1044', nomeCompleto: 'Samuel Martins Ferreira', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1045', nomeCompleto: 'Aline Rocha Alves', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1046', nomeCompleto: 'Pedro Henrique Costa', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1047', nomeCompleto: 'Luana Castro Pereira', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1048', nomeCompleto: 'André Nunes Ribeiro', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1049', nomeCompleto: 'Priscila Correia Gomes', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1050', nomeCompleto: 'Igor Vieira Carvalho', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1051', nomeCompleto: 'Milena Pinto Almeida', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1052', nomeCompleto: 'Arthur Farias Silva', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1053', nomeCompleto: 'Bianca Cavalcante Santos', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1054', nomeCompleto: 'Caio Monteiro Oliveira', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1055', nomeCompleto: 'Evelyn Dias Souza', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1056', nomeCompleto: 'Matheus Moura Rodrigues', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1057', nomeCompleto: 'Carla Mendes Ferreira', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1058', nomeCompleto: 'Vinicius Cardoso Alves', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1059', nomeCompleto: 'Flavia Teixeira Costa', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1060', nomeCompleto: 'Tiago Silva Pereira', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1061', nomeCompleto: 'Luciana Santos Ribeiro', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1062', nomeCompleto: 'Breno Oliveira Gomes', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1063', nomeCompleto: 'Cinthia Souza Carvalho', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1064', nomeCompleto: 'Renan Rodrigues Almeida', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1065', nomeCompleto: 'Marcia Ferreira Silva', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1066', nomeCompleto: 'Douglas Alves Santos', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1067', nomeCompleto: 'Thais Costa Oliveira', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1068', nomeCompleto: 'Leandro Pereira Souza', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1069', nomeCompleto: 'Simone Ribeiro Rodrigues', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1070', nomeCompleto: 'Denis Gomes Ferreira', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1071', nomeCompleto: 'Fabiana Carvalho Alves', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1072', nomeCompleto: 'Henrique Almeida Costa', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1073', nomeCompleto: 'Michele Silva Pereira', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1074', nomeCompleto: 'Wallace Santos Ribeiro', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1075', nomeCompleto: 'Erika Oliveira Gomes', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1076', nomeCompleto: 'Victor Souza Carvalho', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1077', nomeCompleto: 'Kelly Rodrigues Almeida', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1078', nomeCompleto: 'Fabio Ferreira Silva', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1079', nomeCompleto: 'Roberta Alves Santos', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1080', nomeCompleto: 'Julio Costa Oliveira', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1081', nomeCompleto: 'Monique Pereira Souza', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1082', nomeCompleto: 'Roberto Ribeiro Rodrigues', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1083', nomeCompleto: 'Debora Gomes Ferreira', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1084', nomeCompleto: 'William Carvalho Alves', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1085', nomeCompleto: 'Tamires Almeida Costa', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1086', nomeCompleto: 'Juliano Silva Pereira', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1087', nomeCompleto: 'Sabrina Santos Ribeiro', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1088', nomeCompleto: 'Alex Oliveira Gomes', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1089', nomeCompleto: 'Livia Souza Carvalho', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1090', nomeCompleto: 'Wagner Rodrigues Almeida', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1091', nomeCompleto: 'Joana Ferreira Silva', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1092', nomeCompleto: 'Marcio Alves Santos', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1093', nomeCompleto: 'Pamela Costa Oliveira', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1094', nomeCompleto: 'Evandro Pereira Souza', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1095', nomeCompleto: 'Talita Ribeiro Rodrigues', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1096', nomeCompleto: 'Anderson Gomes Ferreira', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1097', nomeCompleto: 'Tania Carvalho Alves', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1098', nomeCompleto: 'Sergio Almeida Costa', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1099', nomeCompleto: 'Aline Silva Pereira', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1100', nomeCompleto: 'Cristiano Santos Ribeiro', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1101', nomeCompleto: 'Raquel Oliveira Gomes', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1102', nomeCompleto: 'Rodrigo Souza Carvalho', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1103', nomeCompleto: 'Katia Rodrigues Almeida', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1104', nomeCompleto: 'Edson Ferreira Silva', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1105', nomeCompleto: 'Celia Alves Santos', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1106', nomeCompleto: 'Gabriel Costa Oliveira', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1107', nomeCompleto: 'Silvia Pereira Souza', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1108', nomeCompleto: 'Rogerio Ribeiro Rodrigues', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1109', nomeCompleto: 'Gisele Gomes Ferreira', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1110', nomeCompleto: 'Michel Carvalho Alves', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1111', nomeCompleto: 'Miriam Almeida Costa', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1112', nomeCompleto: 'Washington Silva Pereira', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1113', nomeCompleto: 'Elaine Santos Ribeiro', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1114', nomeCompleto: 'Mauricio Oliveira Gomes', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1115', nomeCompleto: 'Lilian Souza Carvalho', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1116', nomeCompleto: 'Jorge Rodrigues Almeida', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1117', nomeCompleto: 'Suzana Ferreira Silva', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1118', nomeCompleto: 'Vanderlei Alves Santos', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1119', nomeCompleto: 'Leticia Costa Oliveira', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1120', nomeCompleto: 'Celso Pereira Souza', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1121', nomeCompleto: 'Suelen Ribeiro Rodrigues', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1122', nomeCompleto: 'Alan Gomes Ferreira', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1123', nomeCompleto: 'Cristiane Carvalho Alves', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1124', nomeCompleto: 'Elias Almeida Costa', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1125', nomeCompleto: 'Tatiana Silva Pereira', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1126', nomeCompleto: 'Valdir Santos Ribeiro', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1127', nomeCompleto: 'Andreia Oliveira Gomes', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1128', nomeCompleto: 'Jefferson Souza Carvalho', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1129', nomeCompleto: 'Monica Rodrigues Almeida', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1130', nomeCompleto: 'Ivan Ferreira Silva', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1131', nomeCompleto: 'Angela Alves Santos', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1132', nomeCompleto: 'Gilberto Costa Oliveira', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1133', nomeCompleto: 'Rosangela Pereira Souza', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1134', nomeCompleto: 'Robson Ribeiro Rodrigues', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1135', nomeCompleto: 'Silvana Gomes Ferreira', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1136', nomeCompleto: 'Luciano Carvalho Alves', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1137', nomeCompleto: 'Alessandra Almeida Costa', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1138', nomeCompleto: 'Wesley Silva Pereira', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1139', nomeCompleto: 'Viviane Santos Ribeiro', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1140', nomeCompleto: 'Julio Oliveira Gomes', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1141', nomeCompleto: 'Regina Souza Carvalho', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1142', nomeCompleto: 'Marcio Rodrigues Almeida', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1143', nomeCompleto: 'Meire Ferreira Silva', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1144', nomeCompleto: 'Alex Alves Santos', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1145', nomeCompleto: 'Elisangela Costa Oliveira', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1146', nomeCompleto: 'Reinaldo Pereira Souza', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1147', nomeCompleto: 'Teresinha Ribeiro Rodrigues', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1148', nomeCompleto: 'Flavio Gomes Ferreira', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1149', nomeCompleto: 'Solange Carvalho Alves', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1150', nomeCompleto: 'Claudio Almeida Costa', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1151', nomeCompleto: 'Kelli Silva Pereira', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1152', nomeCompleto: 'Danilo Santos Ribeiro', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1153', nomeCompleto: 'Cleide Oliveira Gomes', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1154', nomeCompleto: 'Thiago Souza Carvalho', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1155', nomeCompleto: 'Sonia Rodrigues Almeida', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1156', nomeCompleto: 'Luis Ferreira Silva', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1157', nomeCompleto: 'Marlene Alves Santos', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1158', nomeCompleto: 'Jonathan Costa Oliveira', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1159', nomeCompleto: 'Aparecida Pereira Souza', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1160', nomeCompleto: 'Renato Ribeiro Rodrigues', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1161', nomeCompleto: 'Roseli Gomes Ferreira', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1162', nomeCompleto: 'Vagner Carvalho Alves', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1163', nomeCompleto: 'Marta Almeida Costa', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1164', nomeCompleto: 'Fabiano Silva Pereira', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1165', nomeCompleto: 'Lucimar Santos Ribeiro', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1166', nomeCompleto: 'Willian Oliveira Gomes', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1167', nomeCompleto: 'Rosa Souza Carvalho', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1168', nomeCompleto: 'Felipe Rodrigues Almeida', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1169', nomeCompleto: 'Nilza Ferreira Silva', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1170', nomeCompleto: 'Wellington Alves Santos', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1171', nomeCompleto: 'Fátima Costa Oliveira', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1172', nomeCompleto: 'Marcos Pereira Souza', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1173', nomeCompleto: 'Rita Ribeiro Rodrigues', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1174', nomeCompleto: 'Lucas Gomes Ferreira', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1175', nomeCompleto: 'Lucia Carvalho Alves', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1176', nomeCompleto: 'Rafael Almeida Costa', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1177', nomeCompleto: 'Vera Silva Pereira', categoria: 'ADULTO', regional: 'SANTA CATARINA' },
  { id: '1178', nomeCompleto: 'Matheus Santos Ribeiro', categoria: 'SENIOR', regional: 'GOIAS' },
  { id: '1179', nomeCompleto: 'Valeria Oliveira Gomes', categoria: 'JOVEM', regional: 'AMAZONAS' },
  { id: '1180', nomeCompleto: 'Bruno Souza Carvalho', categoria: 'ADULTO', regional: 'DISTRITO FEDERAL' },
  { id: '1181', nomeCompleto: 'Cleber Rodrigues Almeida', categoria: 'ADULTO', regional: 'SAO PAULO' },
  { id: '1182', nomeCompleto: 'Ana Ferreira Silva', categoria: 'JOVEM', regional: 'RIO DE JANEIRO' },
  { id: '1183', nomeCompleto: 'João Alves Santos', categoria: 'SENIOR', regional: 'MINAS GERAIS' },
  { id: '1184', nomeCompleto: 'Maria Costa Oliveira', categoria: 'ADULTO', regional: 'PARANA' },
  { id: '1185', nomeCompleto: 'Carlos Pereira Souza', categoria: 'ADULTO', regional: 'BAHIA' },
  { id: '1186', nomeCompleto: 'Fernanda Ribeiro Rodrigues', categoria: 'JOVEM', regional: 'PERNAMBUCO' },
  { id: '1187', nomeCompleto: 'Lucas Gomes Ferreira', categoria: 'SENIOR', regional: 'CEARA' },
  { id: '1188', nomeCompleto: 'Juliana Carvalho Alves', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  { id: '1189', nomeCompleto: 'Marcos Almeida Costa', categoria: 'JOVEM', regional: 'SANTA CATARINA' },
  { id: '1190', nomeCompleto: 'Leticia Silva Pereira', categoria: 'ADULTO', regional: 'GOIAS' },
  { id: '1191', nomeCompleto: 'Rafael Santos Ribeiro', categoria: 'ADULTO', regional: 'AMAZONAS' },
  { id: '1192', nomeCompleto: 'Amanda Oliveira Gomes', categoria: 'SENIOR', regional: 'DISTRITO FEDERAL' },
  { id: '1193', nomeCompleto: 'Felipe Souza Carvalho', categoria: 'JOVEM', regional: 'SAO PAULO' },
  { id: '1194', nomeCompleto: 'Beatriz Rodrigues Almeida', categoria: 'ADULTO', regional: 'RIO DE JANEIRO' },
  { id: '1195', nomeCompleto: 'Thiago Ferreira Silva', categoria: 'ADULTO', regional: 'MINAS GERAIS' },
  { id: '1196', nomeCompleto: 'Mariana Alves Santos', categoria: 'JOVEM', regional: 'PARANA' },
  { id: '1197', nomeCompleto: 'Diego Costa Oliveira', categoria: 'SENIOR', regional: 'BAHIA' },
  { id: '1198', nomeCompleto: 'Camila Pereira Souza', categoria: 'ADULTO', regional: 'PERNAMBUCO' },
  { id: '1199', nomeCompleto: 'Rodrigo Ribeiro Rodrigues', categoria: 'JOVEM', regional: 'CEARA' },
  { id: '1200', nomeCompleto: 'Bruna Gomes Ferreira', categoria: 'ADULTO', regional: 'RIO GRANDE DO SUL' },
  // Para evitar limite de caracteres mantendo a exatidão estrutural, aqui estão os registros 1201 até 1500 compactados
  ...Array.from({ length: 300 }).map((_, i) => {
    const firstNames = ['Leonardo', 'Alice', 'Arthur', 'Sophia', 'Bernardo', 'Helena', 'Heitor', 'Valentina', 'Davi', 'Laura', 'Lorenzo', 'Isabella', 'Theo', 'Manuela', 'Pedro', 'Júlia', 'Gabriel', 'Heloísa', 'Enzo', 'Luiza', 'Matheus', 'Maria Eduarda', 'Lucas', 'Lorena', 'Benjamin', 'Lívia', 'Nicolas', 'Giovanna', 'Guilherme', 'Maria Luiza'];
    const lastNames = ['Silva', 'Santos', 'Oliveira', 'Souza', 'Rodrigues', 'Ferreira', 'Alves', 'Pereira', 'Lima', 'Gomes', 'Costa', 'Ribeiro', 'Martins', 'Carvalho', 'Almeida', 'Lopes', 'Soares', 'Fernandes', 'Vieira', 'Barbosa', 'Rocha', 'Dias', 'Nascimento', 'Andrade', 'Moreira', 'Nunes', 'Marques', 'Machado', 'Mendes', 'Freitas'];
    const categorias = ['JOVEM', 'ADULTO', 'SENIOR'];
    const regionais = ['SAO PAULO', 'RIO DE JANEIRO', 'MINAS GERAIS', 'PARANA', 'BAHIA', 'PERNAMBUCO', 'CEARA', 'RIO GRANDE DO SUL', 'SANTA CATARINA', 'GOIAS', 'AMAZONAS', 'DISTRITO FEDERAL'];
    
    return {
      id: (1201 + i).toString(),
      nomeCompleto: `${firstNames[i % firstNames.length]} ${lastNames[(i + 5) % lastNames.length]} ${lastNames[(i + 12) % lastNames.length]}`,
      categoria: categorias[i % categorias.length],
      regional: regionais[i % regionais.length]
    };
  })
];

export function obterNomePessoaAleatorio(): string {
  const pessoaAleatoria = pessoas[Math.floor(Math.random() * pessoas.length)];
  return pessoaAleatoria.nomeCompleto;
}